services:
  redis-server:
    build: 
      context: ./containers/redisServer
    container_name: redis-server
    image: blindcoder-redis-server
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - my-app-network
    env_file:
      - .env
  
  worker:
    build:
      context: ./containers/worker
    container_name: worker
    image: blindcoder-worker
    depends_on:
      - redis-server
    networks:
      - my-app-network
    env_file:
      - .env

  mongo-db:
    build:
      context: .
      dockerfile: ./containers/mongodb/Dockerfile
    container_name: mongo-db
    image: blindcoder-mongo-db
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - my-app-network
    env_file:
      - .env
  
networks:
  my-app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local